{
  "error": "An exception occurred during backtesting: 'NoneType' object is not subscriptable",
  "traceback": [
    "Traceback (most recent call last):\n  File \"/backend-api/routers/manage_backtesting.py\", line 83, in run_backtesting\n    backtesting_results = await backtesting_engine.run_backtesting(\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/backend-api/lib/python3.12/site-packages/hummingbot/strategy_v2/backtesting/backtesting_engine_base.py\", line 96, in run_backtesting\n    await self.controller.update_processed_data()\n  File \"/backend-api/bots/controllers/directional_trading/dman_v3.py\", line 158, in update_processed_data\n    df = self.market_data_provider.get_candles_df(connector_name=self.config.candles_connector,\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/backend-api/utils/candles_cache.py\", line 201, in cached_get_candles_df\n    return original_fn(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/backend-api/lib/python3.12/site-packages/hummingbot/strategy_v2/backtesting/backtesting_data_provider.py\", line 128, in get_candles_df\n    return candles_df[(candles_df[\"timestamp\"] >= self.start_time) & (candles_df[\"timestamp\"] <= self.end_time)]\n                       ~~~~~~~~~~^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable\n"
  ]
}